<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yoris Daka Pradana Yudha">
<meta name="dcterms.date" content="2025-01-11">

<title>Analisis Determinan Daya Saing Ekspor Batubara Indonesia ke China: Studi Kasus Periode 2013-2023</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="index_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="index_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analisis Determinan Daya Saing Ekspor Batubara Indonesia ke China: Studi Kasus Periode 2013-2023</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yoris Daka Pradana Yudha </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 11, 2025</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
<div style="text-align: justify">
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Indonesia merupakan salah satu produsen dan eksportir batubara terbesar di dunia dengan kontribusi signifikan terhadap perdagangan global. Dengan cadangan batubara yang besar dan kualitas yang beragam, Indonesia memiliki keunggulan komparatif dalam industri ini, terutama dalam memasok kebutuhan energi ke negara-negara Asia seperti China, India, Jepang, dan Korea Selatan.</p>
<p>Dalam konteks perekonomian global yang semakin terintegrasi, daya saing ekspor batubara Indonesia dipengaruhi oleh berbagai faktor. Harga batubara global, sebagai indikator penting, mencerminkan dinamika pasar dan mempengaruhi keputusan perdagangan. Kualitas batubara yang diukur melalui nilai kalori juga menjadi pertimbangan utama bagi negara importir dalam memilih pemasok. Sementara itu, total permintaan dari negara-negara tujuan utama ekspor menggambarkan potensi pasar dan kapasitas penyerapan.</p>
<p>China, sebagai negara dengan tingkat konsumsi energi yang sangat tinggi, telah menjadi pasar utama bagi ekspor batubara Indonesia. Permintaan batubara dari China terus meningkat seiring dengan pertumbuhan ekonominya yang pesat, urbanisasi, dan industrialisasi yang berkelanjutan. Dalam hal ini, posisi Indonesia sebagai pemasok utama batubara ke China mencerminkan hubungan perdagangan yang kuat antara kedua negara. Keterlibatan Indonesia dalam memenuhi kebutuhan energi China juga tidak terlepas dari peran batubara sebagai sumber energi yang mendominasi dalam bauran energi China, meskipun negara tersebut mulai beralih ke energi terbarukan secara bertahap.</p>
<p>Daya saing ekspor batubara Indonesia ke China dipengaruhi oleh sejumlah faktor penting, termasuk harga batubara global yang fluktuatif, kualitas batubara yang diukur melalui nilai kalori, dan kapasitas penyerapan pasar di China. Harga batubara global, yang sering kali dipengaruhi oleh dinamika permintaan dan penawaran internasional, berperan besar dalam menentukan volume ekspor. Kualitas batubara menjadi faktor lain yang tidak kalah penting, karena China cenderung mengimpor batubara dengan spesifikasi tertentu yang sesuai dengan kebutuhan industrinya. Selain itu, kebijakan energi China, termasuk pembatasan impor dan peraturan lingkungan, turut memengaruhi pola perdagangan batubara dengan Indonesia.</p>
<p>Melalui penelitian ini, diharapkan dapat diperoleh pemahaman yang lebih mendalam mengenai daya saing ekspor batubara Indonesia ke China. Fokus penelitian mencakup pengaruh harga batubara, kualitas (kalori), dan total permintaan dari China terhadap volume ekspor. Analisis ini juga bertujuan untuk mengevaluasi posisi kompetitif Indonesia di pasar batubara China, memberikan wawasan yang dapat mendukung pengambilan kebijakan strategis di sektor energi dan perdagangan internasional.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p><strong>Ruang Lingkup Penelitian</strong></p>
<p>Penelitian ini difokuskan pada analisis daya saing ekspor batubara Indonesia ke negara tujuan utama (China) 2013-2023. Data yang digunakan mencakup volume ekspor batubara Indonesia dari Badan Pusat Statistik dan Kementerian ESDM, serta data total impor batubara tujuan dari sumber resmi seperti China Customs Statistics dan UN Comtrade.</p>
<p>Variabel yang dianalisis meliputi:</p>
<ul>
<li><p>Variabel Dependen: Market Share (rasio volume ekspor Indonesia terhadap total impor negara tujuan)</p></li>
<li><p>Variabel Independen:</p>
<ol type="1">
<li><p>Harga batubara global (USD/ton)</p></li>
<li><p>Kualitas batubara (nilai kalori kcal/kg)</p></li>
<li><p>Total permintaan (jumlah impor negara tujuan)</p></li>
<li><p>Growth rate ekspor Indonesia</p></li>
</ol></li>
</ul>
<p>Menggunakan analisis regresi dan visualisasi data, penelitian bertujuan mengidentifikasi faktor-faktor yang mempengaruhi daya saing ekspor batubara Indonesia di pasar China.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Berdasarkan latar belakang yang telah dipaparkan, rumusan masalah penelitian adalah sebagai berikut:</p>
<ol type="1">
<li><p>Bagaimana pengaruh harga batubara global terhadap market share ekspor batubara Indonesia ke China periode 2013-2023?</p></li>
<li><p>Bagaimana pengaruh kualitas batubara (nilai kalori) terhadap market share ekspor batubara Indonesia ke negara tujuan utama?</p></li>
<li><p>Apakah total permintaan dari negara tujuan memiliki pengaruh signifikan terhadap daya saing ekspor batubara Indonesia?</p></li>
<li><p>Bagaimana pengaruh growth rate ekspor terhadap posisi kompetitif Indonesia di pasar batubara global?</p></li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Berdasarkan latar belakang dan rumusan masalah, tujuan penelitian ini adalah menganalisis faktor-faktor yang mempengaruhi daya saing ekspor batubara Indonesia ke China periode 2013-2023, dengan rincian:</p>
<ul>
<li><p>Menganalisis pengaruh harga batubara global terhadap market share ekspor batubara Indonesia</p></li>
<li><p>Mengukur dampak kualitas batubara (nilai kalori) terhadap daya saing ekspor</p></li>
<li><p>Mengidentifikasi pengaruh total permintaan negara tujuan terhadap market share Indonesia</p></li>
<li><p>Menganalisis hubungan growth rate ekspor dengan posisi kompetitif Indonesia</p></li>
</ul>
<p><strong>Manfaat Praktis:</strong></p>
<ul>
<li><p>Masukan untuk kebijakan ekspor batubara</p></li>
<li><p>Evaluasi strategi peningkatan daya saing</p></li>
<li><p>Optimalisasi kebijakan kualitas dan harga</p></li>
<li><p>Informasi trend pasar batubara global</p></li>
<li><p>Strategi penetapan standar kualitas</p></li>
<li><p>Pemahaman faktor daya saing ekspor</p></li>
</ul>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p><strong>1. Teori Perdagangan Internasional</strong></p>
<p>Perdagangan internasional merupakan kegiatan pertukaran barang, jasa dan modal yang melintasi batas teritorial antara suatu negara dengan negara lain. Menurut Salvatore (2013), perdagangan internasional dapat menjadi mesin pertumbuhan bagi negara berkembang, dimana melalui aktivitas ini, suatu negara dapat mengoptimalkan keunggulan komparatif yang dimilikinya.</p>
<p><strong>2. Ekspor</strong></p>
<p>Ekspor adalah kegiatan menjual barang dari dalam negeri ke luar negeri dengan mengikuti ketentuan yang berlaku. Menurut Tambunan (2001), ekspor memiliki peranan strategis dalam:</p>
<ol type="1">
<li><p>Memperluas pasar bagi produk Indonesia</p></li>
<li><p>Menambah devisa negara</p></li>
<li><p>Memperluas lapangan kerja</p></li>
</ol>
<p><strong>3. Daya Saing</strong></p>
<p>Daya saing merupakan kemampuan suatu komoditas untuk memasuki pasar luar negeri dan kemampuan untuk bertahan dalam pasar tersebut (Porter, 1990). Tingkat daya saing suatu negara dalam perdagangan internasional ditentukan oleh dua faktor yaitu faktor keunggulan komparatif (comparative advantage) dan faktor keunggulan kompetitif (competitive advantage).</p>
<p><strong>4. Batubara</strong></p>
<p>Daya saing merupakan kemampuan suatu komoditas untuk memasuki pasar luar negeri dan kemampuan untuk bertahan dalam pasar tersebut (Porter, 1990). Tingkat daya saing suatu negara dalam perdagangan internasional ditentukan oleh dua faktor yaitu faktor keunggulan komparatif (comparative advantage) dan faktor keunggulan kompetitif (competitive advantage).</p>
<p><strong>5. Revealed Comparative Advantage</strong></p>
<p>RCA adalah metode untuk mengukur keunggulan komparatif suatu negara dalam mengekspor suatu barang dibandingkan dengan negara-negara lain di dunia. Balassa (1965) memperkenalkan metode ini dengan formula: RCA = (Xij/Xit)/(Wj/Wt)</p>
<p>Dimana:</p>
<ul>
<li><p>Xij = Nilai ekspor komoditas j dari negara i</p></li>
<li><p>Xit = Nilai total ekspor negara i</p></li>
<li><p>Wj = Nilai ekspor komoditas j dunia</p></li>
<li><p>Wt = Nilai total ekspor dunia</p></li>
</ul>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Data yang saya gunakan adalah data volume ekspor batubara indonesia, data total impor negara tujuan, data harga global batubara, dan data kalori untuk mengetahui kualitas batubara.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data 2013-2023 fokus pada China</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Tahun =</span> <span class="dv">2013</span><span class="sc">:</span><span class="dv">2023</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Ekspor_Total_Indonesia =</span> <span class="fu">c</span>(<span class="fl">424.3</span>, <span class="fl">435.2</span>, <span class="fl">461.6</span>, <span class="fl">456.2</span>, <span class="fl">490.6</span>, <span class="fl">510.4</span>, <span class="fl">454.5</span>, <span class="fl">405.1</span>, <span class="fl">434.5</span>, <span class="fl">482.4</span>, <span class="fl">498.7</span>),</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Ekspor_ke_China =</span> <span class="fu">c</span>(<span class="fl">89.78</span>, <span class="fl">49.78</span>, <span class="fl">36.68</span>, <span class="fl">50.84</span>, <span class="fl">48.17</span>, <span class="fl">48.14</span>, <span class="fl">65.67</span>, <span class="fl">62.49</span>, <span class="fl">108.49</span>, <span class="fl">69.69</span>, <span class="fl">81.68</span>),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Impor_Total_China =</span> <span class="fu">c</span>(<span class="fl">752.3</span>, <span class="fl">823.5</span>, <span class="fl">832.1</span>, <span class="fl">845.6</span>, <span class="fl">889.2</span>, <span class="fl">925.4</span>, <span class="fl">933.2</span>, <span class="fl">945.6</span>, <span class="fl">952.3</span>, <span class="fl">965.4</span>, <span class="fl">978.2</span>),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Harga =</span> <span class="fu">c</span>(<span class="fl">82.9</span>, <span class="fl">72.6</span>, <span class="fl">60.1</span>, <span class="fl">61.8</span>, <span class="fl">87.39</span>, <span class="fl">105.73</span>, <span class="fl">78.44</span>, <span class="fl">61.21</span>, <span class="fl">134.34</span>, <span class="fl">345.41</span>, <span class="fl">172.05</span>),</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Kalori =</span> <span class="fu">c</span>(<span class="dv">5150</span>, <span class="dv">5200</span>, <span class="dv">5180</span>, <span class="dv">5250</span>, <span class="dv">5300</span>, <span class="dv">5280</span>, <span class="dv">5260</span>, <span class="dv">5320</span>, <span class="dv">5350</span>, <span class="dv">5400</span>, <span class="dv">5450</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Transform data</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">Growth_Rate =</span> (Ekspor_ke_China<span class="sc">/</span><span class="fu">lag</span>(Ekspor_ke_China) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">Price_Index =</span> Harga<span class="sc">/</span><span class="fu">mean</span>(Harga) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">Market_Share =</span> Ekspor_ke_China<span class="sc">/</span>Impor_Total_China <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Cetak tabel dengan kable</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="st">"html"</span>, <span class="at">caption =</span> <span class="st">"Data Batubara"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>, <span class="st">"responsive"</span>, <span class="st">"bordered"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed table-bordered table-sm small" data-quarto-postprocess="true">
<caption>Data Batubara</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Tahun</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Ekspor_Total_Indonesia</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Ekspor_ke_China</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Impor_Total_China</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Harga</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Kalori</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Growth_Rate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Price_Index</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Market_Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2013</td>
<td style="text-align: right;">424.3</td>
<td style="text-align: right;">89.78</td>
<td style="text-align: right;">752.3</td>
<td style="text-align: right;">82.90</td>
<td style="text-align: right;">5150</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">72.26004</td>
<td style="text-align: right;">11.934069</td>
</tr>
<tr class="even">
<td style="text-align: right;">2014</td>
<td style="text-align: right;">435.2</td>
<td style="text-align: right;">49.78</td>
<td style="text-align: right;">823.5</td>
<td style="text-align: right;">72.60</td>
<td style="text-align: right;">5200</td>
<td style="text-align: right;">-44.5533526</td>
<td style="text-align: right;">63.28201</td>
<td style="text-align: right;">6.044930</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2015</td>
<td style="text-align: right;">461.6</td>
<td style="text-align: right;">36.68</td>
<td style="text-align: right;">832.1</td>
<td style="text-align: right;">60.10</td>
<td style="text-align: right;">5180</td>
<td style="text-align: right;">-26.3157895</td>
<td style="text-align: right;">52.38635</td>
<td style="text-align: right;">4.408124</td>
</tr>
<tr class="even">
<td style="text-align: right;">2016</td>
<td style="text-align: right;">456.2</td>
<td style="text-align: right;">50.84</td>
<td style="text-align: right;">845.6</td>
<td style="text-align: right;">61.80</td>
<td style="text-align: right;">5250</td>
<td style="text-align: right;">38.6041439</td>
<td style="text-align: right;">53.86816</td>
<td style="text-align: right;">6.012299</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2017</td>
<td style="text-align: right;">490.6</td>
<td style="text-align: right;">48.17</td>
<td style="text-align: right;">889.2</td>
<td style="text-align: right;">87.39</td>
<td style="text-align: right;">5300</td>
<td style="text-align: right;">-5.2517703</td>
<td style="text-align: right;">76.17376</td>
<td style="text-align: right;">5.417229</td>
</tr>
<tr class="even">
<td style="text-align: right;">2018</td>
<td style="text-align: right;">510.4</td>
<td style="text-align: right;">48.14</td>
<td style="text-align: right;">925.4</td>
<td style="text-align: right;">105.73</td>
<td style="text-align: right;">5280</td>
<td style="text-align: right;">-0.0622794</td>
<td style="text-align: right;">92.15988</td>
<td style="text-align: right;">5.202075</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2019</td>
<td style="text-align: right;">454.5</td>
<td style="text-align: right;">65.67</td>
<td style="text-align: right;">933.2</td>
<td style="text-align: right;">78.44</td>
<td style="text-align: right;">5260</td>
<td style="text-align: right;">36.4146240</td>
<td style="text-align: right;">68.37247</td>
<td style="text-align: right;">7.037077</td>
</tr>
<tr class="even">
<td style="text-align: right;">2020</td>
<td style="text-align: right;">405.1</td>
<td style="text-align: right;">62.49</td>
<td style="text-align: right;">945.6</td>
<td style="text-align: right;">61.21</td>
<td style="text-align: right;">5320</td>
<td style="text-align: right;">-4.8423938</td>
<td style="text-align: right;">53.35388</td>
<td style="text-align: right;">6.608503</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2021</td>
<td style="text-align: right;">434.5</td>
<td style="text-align: right;">108.49</td>
<td style="text-align: right;">952.3</td>
<td style="text-align: right;">134.34</td>
<td style="text-align: right;">5350</td>
<td style="text-align: right;">73.6117779</td>
<td style="text-align: right;">117.09787</td>
<td style="text-align: right;">11.392418</td>
</tr>
<tr class="even">
<td style="text-align: right;">2022</td>
<td style="text-align: right;">482.4</td>
<td style="text-align: right;">69.69</td>
<td style="text-align: right;">965.4</td>
<td style="text-align: right;">345.41</td>
<td style="text-align: right;">5400</td>
<td style="text-align: right;">-35.7636649</td>
<td style="text-align: right;">301.07768</td>
<td style="text-align: right;">7.218769</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2023</td>
<td style="text-align: right;">498.7</td>
<td style="text-align: right;">81.68</td>
<td style="text-align: right;">978.2</td>
<td style="text-align: right;">172.05</td>
<td style="text-align: right;">5450</td>
<td style="text-align: right;">17.2047640</td>
<td style="text-align: right;">149.96791</td>
<td style="text-align: right;">8.350031</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Sumber data: UN Comtrade, Kementerian ESDM.</p>
</section>
<section id="plot-data" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="plot-data"><span class="header-section-number">3.2</span> Plot Data</h3>
<p><strong>Tren Market Share China</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Tren Market Share di China</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Tahun, <span class="at">y =</span> Market_Share)) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Tren Market Share Batubara Indonesia di China"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Market Share (%)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/fig-1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Tren Market Share China</figcaption>
</figure>
</div>
</div>
</div>
<p>Tren market share batubara Indonesia di pasar China menunjukkan dinamika yang sangat fluktuatif selama periode yang ditampilkan, kira-kira dari tahun 2013 hingga 2023. Grafik memperlihatkan penurunan tajam di awal periode dari posisi sekitar 12% menjadi kurang dari 5% pada tahun 2015. Setelah mencapai titik terendah ini, market share Indonesia mengalami periode stabilisasi selama dua tahun berikutnya, berkisar antara 5-6%. Mulai tahun 2017, terlihat adanya peningkatan bertahap yang kemudian diikuti oleh lonjakan signifikan pada tahun 2021, di mana market share kembali mencapai sekitar 11%. Namun, pencapaian ini tidak bertahan lama karena terjadi penurunan tajam di tahun berikutnya, meskipun ada indikasi pemulihan menjelang akhir periode.</p>
<p>Volatilitas tinggi yang terlihat dalam grafik ini mengindikasikan kompleksitas dan dinamika pasar batubara antara Indonesia dan China. Meskipun terdapat fluktuasi yang ekstrem, ada tren umum peningkatan market share jika dilihat dari titik terendah di 2015 hingga akhir periode. Pola ini menunjukkan resiliensi industri batubara Indonesia dalam menghadapi berbagai tantangan pasar. Fluktuasi yang terjadi kemungkinan besar dipengaruhi oleh beragam faktor, termasuk perubahan kebijakan impor China, dinamika permintaan energi, persaingan dari negara eksportir lain, serta perubahan dalam produksi batubara domestik China. Grafik ini menegaskan pentingnya analisis mendalam terhadap faktor-faktor yang mempengaruhi daya saing ekspor batubara Indonesia ke China, mengingat posisi Indonesia yang sangat dinamis dan rentan terhadap perubahan kondisi pasar global maupun kebijakan bilateral kedua negara.</p>
<p><strong>Plot Market Share vs Variabel Independen</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Hubungan Market Share dengan Variabel Independen</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Price_Index, <span class="at">y =</span> Market_Share)) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Market Share vs Harga"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Indeks Harga"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Market Share (%)"</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Growth_Rate, <span class="at">y =</span> Market_Share)) <span class="sc">+</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Market Share vs Growth Rate"</span>,</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Growth Rate (%)"</span>,</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Market Share (%)"</span>)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Impor_Total_China, <span class="at">y =</span> Market_Share)) <span class="sc">+</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Market Share vs Total Impor China"</span>,</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Total Impor China (Juta Ton)"</span>,</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Market Share (%)"</span>)</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Kalori, <span class="at">y =</span> Market_Share)) <span class="sc">+</span></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Market Share vs Kalori"</span>,</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Kalori"</span>,</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Market Share (%)"</span>)</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, p3, p4, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/fig-2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Market Share vs Variabel Independen</figcaption>
</figure>
</div>
</div>
</div>
<p>Interpretasi dari empat plot yang ditampilkan adalah sebagai berikut:</p>
<ol type="1">
<li><p>Market Share vs Harga: Plot ini menunjukkan hubungan positif lemah antara indeks harga dan market share. Meskipun ada tren peningkatan market share seiring dengan kenaikan harga, sebaran data cukup luas, yang menunjukkan bahwa faktor harga bukanlah satu-satunya penentu market share. Beberapa titik data yang jauh dari garis tren mengindikasikan adanya faktor-faktor lain yang mempengaruhi market share selain harga.</p></li>
<li><p>Market Share vs Growth Rate: Terdapat korelasi positif yang lebih jelas antara growth rate dan market share. Semakin tinggi tingkat pertumbuhan, semakin tinggi pula market share. Namun, sebaran data masih cukup luas, menunjukkan bahwa hubungan ini tidak sepenuhnya linear dan ada faktor-faktor lain yang berperan.</p></li>
<li><p>Market Share vs Total Impor China: Plot ini menunjukkan hubungan yang hampir datar atau sedikit negatif antara total impor China dan market share Indonesia. Ini mengindikasikan bahwa peningkatan total impor China tidak selalu berkorelasi dengan peningkatan market share Indonesia. Sebaran data yang luas menunjukkan kompleksitas hubungan ini dan kemungkinan adanya faktor-faktor lain yang lebih berpengaruh.</p></li>
<li><p>Market Share vs Kalori: Terdapat hubungan positif lemah antara kalori batubara dan market share. Meskipun ada kecenderungan peningkatan market share seiring dengan peningkatan kalori, hubungan ini tidak terlalu kuat. Sebaran data yang cukup luas menunjukkan bahwa kualitas batubara (yang direpresentasikan oleh kalori) bukanlah satu-satunya faktor penentu market share.</p></li>
</ol>
<p>Secara keseluruhan, plot-plot ini menggambarkan kompleksitas faktor-faktor yang mempengaruhi market share batubara Indonesia di pasar China. Tidak ada satu faktor yang dominan dalam menentukan market share, melainkan kombinasi dari berbagai variabel. Growth rate tampaknya memiliki pengaruh positif yang paling jelas, sementara faktor-faktor lain seperti harga, total impor China, dan kalori batubara memiliki pengaruh yang lebih subtle dan mungkin berinteraksi dengan variabel-variabel lain yang tidak ditampilkan dalam plot ini.</p>
<p><strong>Perbandingan Ekspor ke China vs Total Impor China</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Perbandingan Ekspor ke China dan Total Impor China</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Tahun)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Ekspor_ke_China, <span class="at">color =</span> <span class="st">"Ekspor ke China"</span>)) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Impor_Total_China, <span class="at">color =</span> <span class="st">"Total Impor China"</span>)) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Perbandingan Ekspor Batubara Indonesia ke China dan Total Impor China"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Volume (Juta Ton)"</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Indikator"</span>) <span class="sc">+</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Ekspor ke China"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"Total Impor China"</span> <span class="ot">=</span> <span class="st">"red"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/fig-3-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Ekspor Indonesia ke China vs Total Impor China</figcaption>
</figure>
</div>
</div>
</div>
<p>Plot tersebut menunjukkan perbandingan volume ekspor batubara Indonesia ke China dengan total volume impor batubara China selama periode 2012 hingga 2022. Garis biru menggambarkan ekspor batubara Indonesia ke China, sementara garis merah menunjukkan total impor batubara oleh China. Dari grafik ini terlihat bahwa volume ekspor Indonesia ke China cenderung stabil dengan fluktuasi kecil, sedangkan total impor batubara China terus meningkat secara konsisten. Hal ini menunjukkan bahwa meskipun permintaan batubara di China meningkat, pangsa ekspor batubara Indonesia terhadap total impor China tampaknya tidak mengalami peningkatan yang signifikan. Ini dapat mencerminkan persaingan yang ketat di pasar China atau adanya diversifikasi sumber impor batubara oleh China.</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.3</span> Metode analisis</h3>
<p>Metode yang digunakan dalam penelitian ini adalah Regresi Linier Berganda, yang bertujuan untuk menganalisis pengaruh variabel independen terhadap daya saing ekspor batubara Indonesia ke China, yang diukur melalui pangsa pasar (Market Share). Model ini dirancang untuk mengidentifikasi hubungan antara faktor harga, pertumbuhan volume ekspor, total impor China, dan kualitas batubara dengan daya saing Indonesia. Spesifikasi model regresi yang digunakan adalah sebagai berikut:</p>
<p><em>Model Regresi:</em></p>
<p><span class="math display">\[
\text{Market Share}_t = \beta_0 + \beta_1 \text{Price Index}_t + \beta_2 \text{Growth Rate}_t + \beta_3 \text{Impor Total China}_t + \beta_4 \text{Kalori}_t + \varepsilon_t
\]</span></p>
<p>Dimana:</p>
<ul>
<li><p><span class="math inline">\(\text{Market Share}_t\)</span>: Pangsa pasar ekspor batubara Indonesia di China pada tahun ( t ) (%).</p></li>
<li><p><span class="math inline">\(\text{Price Index}_t\)</span> : Indeks harga batubara relatif terhadap rata-rata periode penelitian pada tahun ( t ) (%).</p></li>
<li><p><span class="math inline">\(\text{Growth Rate}_t\)</span>: Tingkat pertumbuhan ekspor batubara Indonesia ke China dari tahun sebelumnya ke tahun ( t ) (%).</p></li>
<li><p><span class="math inline">\(\text{Impor Total China}_t\)</span>: Total volume impor batubara China pada tahun ( t ) (juta ton).</p></li>
<li><p><span class="math inline">\(\text{Kalori}_t\)</span>: Kualitas batubara berdasarkan nilai kalor (Kcal/kg) pada tahun ( t ).</p></li>
<li><p><span class="math inline">\(\beta_0\)</span>: Intersep model.</p></li>
<li><p><span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\beta_2\)</span>, <span class="math inline">\(\beta_3\)</span>, <span class="math inline">\(\beta_4\)</span>, : Koefisien regresi masing-masing variabel independen.</p></li>
<li><p><span class="math inline">\(\varepsilon_t\)</span>: Error term pada tahun ( t ).</p></li>
</ul>
</section>
<section id="analisis-masalah" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">3.4</span> Analisis Masalah</h3>
<section id="regresi" class="level4" data-number="3.4.1">
<h4 data-number="3.4.1" class="anchored" data-anchor-id="regresi"><span class="header-section-number">3.4.1</span> Regresi</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model regresi untuk China</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>model_china <span class="ot">&lt;-</span> <span class="fu">lm</span>(Market_Share <span class="sc">~</span> Price_Index <span class="sc">+</span> Growth_Rate <span class="sc">+</span> Impor_Total_China <span class="sc">+</span> Kalori, <span class="at">data =</span> data)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistik</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_china)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Market_Share ~ Price_Index + Growth_Rate + Impor_Total_China + 
    Kalori, data = data)

Residuals:
       2        3        4        5        6        7        8        9 
 1.88192 -0.19067 -1.29893 -0.80407 -1.19099 -0.33576  0.44814  1.80413 
      10       11 
-0.22023 -0.09354 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)       -2.564e+01  6.358e+01  -0.403   0.7034  
Price_Index        7.650e-03  1.060e-02   0.722   0.5028  
Growth_Rate        3.522e-02  1.678e-02   2.098   0.0899 .
Impor_Total_China -3.678e-04  1.911e-02  -0.019   0.9854  
Kalori             5.998e-03  1.433e-02   0.419   0.6929  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.48 on 5 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.6881,    Adjusted R-squared:  0.4386 
F-statistic: 2.758 on 4 and 5 DF,  p-value: 0.1478</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(model_china, <span class="at">type =</span> <span class="st">"text"</span>, <span class="at">title =</span> <span class="st">"Hasil Regresi Daya Saing Ekspor Batubara Indonesia ke China"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Hasil Regresi Daya Saing Ekspor Batubara Indonesia ke China
===============================================
                        Dependent variable:    
                    ---------------------------
                           Market_Share        
-----------------------------------------------
Price_Index                    0.008           
                              (0.011)          
                                               
Growth_Rate                   0.035*           
                              (0.017)          
                                               
Impor_Total_China             -0.0004          
                              (0.019)          
                                               
Kalori                         0.006           
                              (0.014)          
                                               
Constant                      -25.638          
                             (63.576)          
                                               
-----------------------------------------------
Observations                    10             
R2                             0.688           
Adjusted R2                    0.439           
Residual Std. Error       1.480 (df = 5)       
F Statistic              2.758 (df = 4; 5)     
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p><strong>Hasil Regresi</strong></p>
<ul>
<li><p><strong>Price Index:</strong> Koefisien sebesar 0.008. menunjukkan bahwa peningkatan indeks harga sebesar 1% dihubungkan dengan peningkatan pangsa pasar sebesar 0.008%. Namun, karena nilai p-nya tidak signifikan ( 𝑝 &gt; 0.1 ), variabel ini tidak memiliki hubungan yang signifikan secara statistik dengan Market Share.</p></li>
<li><p><strong>Growth Rate:</strong> Koefisien sebesar 0.035 menunjukkan bahwa setiap peningkatan tingkat pertumbuhan ekspor sebesar 1% dihubungkan dengan peningkatan pangsa pasar sebesar 0.035%. Dengan nilai 𝑝 &lt; 0.1 (signifikan pada tingkat 10%), variabel ini memiliki hubungan yang signifikan secara statistik dengan Market Share.</p></li>
<li><p><strong>Impor Total China:</strong> Koefisien sebesar − 0.0004. menunjukkan bahwa setiap peningkatan total impor China sebesar 1 juta ton dihubungkan dengan penurunan pangsa pasar sebesar 0.0004%. Namun, nilai p yang tidak signifikan ( 𝑝 &gt; 0.1 ) menunjukkan bahwa variabel ini tidak memiliki hubungan yang signifikan secara statistik dengan Market Share.</p></li>
<li><p><strong>Kalori:</strong> Koefisien sebesar 0.006 menunjukkan bahwa peningkatan kualitas batubara sebesar 1 Kcal/kg dihubungkan dengan peningkatan pangsa pasar sebesar 0.006%. Namun, nilai p yang tidak signifikan ( 𝑝 &gt; 0.1 ) menunjukkan bahwa variabel ini juga tidak signifikan secara statistik.</p></li>
<li><p><strong>Konstanta</strong>: Nilai konstanta sebesar − 25.638 tidak memiliki makna praktis langsung, karena hanya merepresentasikan nilai Market Share saat semua variabel independen bernilai nol, yang jarang terjadi dalam konteks riil.</p></li>
</ul>
</section>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">4</span> Kesimpulan</h2>
<p><strong>Kesimpulan Berdasarkan Hasil Regresi</strong></p>
<p>Berdasarkan analisis regresi yang dilakukan, berikut adalah kesimpulan yang menjawab rumusan masalah penelitian:</p>
<ul>
<li><p><strong>Pengaruh harga batubara global terhadap market share ekspor batubara Indonesia ke China (2013-2023):</strong><br>
Hasil regresi menunjukkan bahwa variabel Price Index memiliki koefisien sebesar 0.008, yang berarti setiap kenaikan indeks harga batubara global sebesar 1% dihubungkan dengan peningkatan pangsa pasar ekspor batubara Indonesia ke China sebesar 0.008%. Namun, nilai p ( <em>p</em> = 0.5028 ) menunjukkan bahwa pengaruh ini tidak signifikan secara statistik . Dengan demikian, harga batubara global tidak memiliki pengaruh signifikan terhadap daya saing ekspor batubara Indonesia di pasar China selama periode penelitian.</p></li>
<li><p><strong>Pengaruh kualitas batubara (nilai kalori) terhadap market share ekspor batubara Indonesia:</strong><br>
Variabel Kalori memiliki koefisien sebesar 0.006, yang berarti peningkatan kualitas batubara sebesar 1 Kcal/kg dihubungkan dengan peningkatan pangsa pasar sebesar 0.006%. Namun, nilai p ( <em>p</em> = 0.6929 ) menunjukkan bahwa pengaruh ini tidak signifikan secara statistik. Artinya, kualitas batubara (nilai kalori) tidak memberikan dampak signifikan terhadap daya saing ekspor Indonesia di pasar China selama periode penelitian.</p></li>
<li><p><strong>Pengaruh total permintaan dari negara tujuan terhadap daya saing ekspor batubara Indonesia:</strong><br>
Variabel Impor_Total_China memiliki koefisien sebesar −0.0004, yang menunjukkan bahwa setiap peningkatan total impor batubara China sebesar 1 juta ton dihubungkan dengan penurunan pangsa pasar Indonesia sebesar 0.0004%. Namun, nilai p ( <em>p</em> = 0.9854 ) menunjukkan bahwa pengaruh ini juga tidak signifikan secara statistik. Dengan demikian, total permintaan batubara dari negara tujuan (China) tidak memiliki pengaruh signifikan terhadap daya saing ekspor batubara Indonesia.</p></li>
<li><p><strong>4. Pengaruh growth rate ekspor terhadap posisi kompetitif Indonesia di pasar batubara global:</strong><br>
Variabel Growth Rate memiliki koefisien sebesar 0.035, yang berarti peningkatan tingkat pertumbuhan ekspor sebesar 1% dihubungkan dengan peningkatan pangsa pasar sebesar 0.035%. Nilai p ( <em>p</em> = 0.0899 ) menunjukkan bahwa pengaruh ini signifikan pada tingkat signifikansi 10%. Artinya, tingkat pertumbuhan ekspor memiliki pengaruh yang signifikan terhadap daya saing ekspor batubara Indonesia di pasar China. Semakin tinggi tingkat pertumbuhan ekspor, semakin besar pangsa pasar yang dapat diraih oleh Indonesia.</p></li>
</ul>
<p><strong>Kesimpulan Akhir:</strong><br>
Dari hasil regresi, hanya growth rate ekspor yang terbukti memiliki pengaruh signifikan terhadap daya saing ekspor batubara Indonesia di China. Faktor lain, seperti harga batubara global, kualitas batubara (nilai kalori), dan total permintaan batubara dari China, tidak memberikan pengaruh yang signifikan selama periode 2013-2023. Hal ini menunjukkan bahwa untuk meningkatkan posisi kompetitif di pasar batubara global, Indonesia perlu mempertahankan atau meningkatkan tingkat pertumbuhan ekspor batubara, selain mempertimbangkan faktor lain yang mungkin relevan di luar model ini.</p>
<p>Growth rate ekspor yang signifikan terhadap daya saing ekspor batubara Indonesia dapat didukung oleh Teori Keunggulan Kompetitif dan Teori Siklus Hidup Produk, yang menekankan pentingnya konsistensi pertumbuhan ekspor dalam mempertahankan posisi di pasar internasional.</p>
<p>Ketidaksignifikanan harga dan kualitas batubara dalam model ini sejalan dengan Teori Elastisitas Permintaan Ekspor dan Teori Permintaan Efektif, yang menunjukkan bahwa faktor lain, seperti diversifikasi sumber impor dan permintaan inelastis, lebih memengaruhi keputusan pembelian negara tujuan seperti China.</p>
</section>
<section id="studi-pustaka-1" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="studi-pustaka-1"><span class="header-section-number">5</span> Studi Pustaka</h2>
<p>Badan Pusat Statistik (BPS). (2023). Ekspor Batubara Indonesia Menurut Negara Tujuan Utama, 2013-2023. Retrieved January 4, 2025, from https://www.bps.go.id</p>
<p>IEEFA (Institute for Energy Economics and Financial Analysis). (2022). Coal Trade Trends and Market Analysis in Southeast Asia. Retrieved January 4, 2025, from https://ieefa.org</p>
<p>International Energy Agency (IEA). (2022). Coal 2022: Analysis and Forecast to 2024. Retrieved January 4, 2025, from https://www.iea.org/reports/coal-2022</p>
<p>Kementerian Energi dan Sumber Daya Mineral Republik Indonesia (KESDM). (2022). Statistik Batubara Indonesia 2022. Direktorat Jenderal Mineral dan Batubara. Retrieved January 4, 2025, from https://www.esdm.go.id</p>
<p>PwC Indonesia. (2022). Mining in Indonesia: Investment and Taxation Guide. Retrieved January 4, 2025, from https://www.pwc.com/id/en</p>
<p>United Nations Comtrade Database. (2023). Trade Statistics for Coal Exports: Indonesia and China. Retrieved January 4, 2025, from https://comtrade.un.org</p>
</section>
</div>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>